// Player skin definitions — each skin has named color slots
export const SKINS = [
  {
    id: 'default',
    name: 'Adventurer',
    emoji: '🧑',
    skin: '#f1c27d',
    shirt: '#00bcd4',
    pants: '#2c3e50',
    hair: '#5c3317',
    accent: '#00bcd4',
  },
  {
    id: 'warrior',
    name: 'Warrior',
    emoji: '⚔️',
    skin: '#c68642',
    shirt: '#7f0000',
    pants: '#111',
    hair: '#1a1a1a',
    accent: '#ff4444',
  },
  {
    id: 'archer',
    name: 'Archer',
    emoji: '🏹',
    skin: '#ffe0b2',
    shirt: '#4a7c3f',
    pants: '#6d4c41',
    hair: '#795548',
    accent: '#8bc34a',
  },
  {
    id: 'mage',
    name: 'Mage',
    emoji: '🧙',
    skin: '#ffe0b2',
    shirt: '#6a0dad',
    pants: '#2d1b6e',
    hair: '#bdbdbd',
    accent: '#ce93d8',
  },
  {
    id: 'robot',
    name: 'Robot',
    emoji: '🤖',
    skin: '#90a4ae',
    shirt: '#37474f',
    pants: '#263238',
    hair: '#546e7a',
    accent: '#00e5ff',
  },
  {
    id: 'builder',
    name: 'Builder',
    emoji: '👷',
    skin: '#f1c27d',
    shirt: '#ffa000',
    pants: '#5d4037',
    hair: '#3e2723',
    accent: '#ff8f00',
  },
  {
    id: 'ghost',
    name: 'Ghost',
    emoji: '👻',
    skin: '#e3f2fd',
    shirt: '#e8eaf6',
    pants: '#c5cae9',
    hair: '#ffffff',
    accent: '#b0bec5',
  },
  {
    id: 'ninja',
    name: 'Ninja',
    emoji: '🥷',
    skin: '#5d4037',
    shirt: '#1a1a1a',
    pants: '#111111',
    hair: '#000000',
    accent: '#ff3d00',
  },
]
